require 'spec_helper'
# require File.join(Rails.root, "lib/spree_products_feed/google_merchant/feed")

describe SpreeProductsFeed::GoogleMerchant::Feed do
  let(:buffer) { StringIO.new }
  let(:product) { create :product, taxons: [create(:taxon)] }
  let(:variants) { create_list(:variant, 2, product: product) }
  let(:feed) {
    SpreeProductsFeed::GoogleMerchant::Feed.new(
      variants,
      {
        currency: Spree::Config[:currency],
        country: Spree::Country.find(Spree::Config[:default_country_id]),
        title: 'Google Merchant feed',
        description: 'Google Merchant feed generated by Spree',
        link: Spree::Store.default.url,
        google_category: 'Software > Digital Goods & Currency',
        target: buffer
      }
    )
  }

  before do
    reset_spree_preferences do |config|
      config.default_country_id = create(:country).id
      config.currency = 'USD'
    end

  end

  it 'initializes a new GoogleMerchant::Feed' do
    expect(feed).to be_a(SpreeProductsFeed::GoogleMerchant::Feed)
  end

  describe '#generate' do
    before do
      feed.generate

      buffer.rewind
      @result = buffer.read
    end

    it 'generates a Google Merchand feed' do
      puts @result
      expect(@result).to_not be_empty
    end
  end
end
