require 'builder'

module ProductsFeed::GoogleMerchant
  class Feed

    def initialize(items, target=STDOUT, options={})
      @items = items
      @target = target

      @options = {
        title: 'Google Merchant feed',
        description: 'Google Merchant feed generated by Spree',
        link: 'http://example.com',
      }.merge(options)
    end

    def generate &block
      @required_fields_left = required_fields.clone

      xml.instruct! :xml, version: '1.0'

      xml.rss(version: '2.0', 'xmlns:g' => 'http://base.google.com/ns/1.0') do
        xml.channel do
          xml.title @options[:title]
          xml.description @options[:description]
          xml.link @options[:link]

          @items.each do |item|
            xml.item do
              yield self, item
            end
          end
        end
      end

      if @required_fields_left.any?
        raise ProductsFeed::MissingMandatoryParamError, "The following fields are missing:\n#{@required_fields_left.join(', ')}"
      end

      xml
    end

    def field(name, value)
      @required_fields_left.delete name

      xml.tag! name, value
    end

    private
    def xml
      @xml ||= Builder::XmlMarkup.new target: @target, indent: 2
    end

    def required_fields
      @required_fields ||= [
        'g:id', 'g:title', 'g:description', 'g:link', 'g:image_link',
        'g:condition', 'g:availability', 'g:price', 'g:brand',
        'g:mpn'
      ]
    end
  end
end
